/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import type { PipelineStage, ShopSettings } from './types';

/** Default pipeline stages used when shop settings omit pipeline_stages. */
export const DEFAULT_PIPELINE_STAGES: PipelineStage[] = [
  { id: 'Pending', name: 'Getting Ready', enabled: true },
  { id: 'Ready to Deliver', name: 'Ready to Deliver', enabled: true },
  { id: 'Delivered', name: 'Delivered', enabled: true },
  { id: 'Archived', name: 'Archived', enabled: true },
];

/**
 * Default shop settings used by the local SQLite server and desktop UI fallbacks.
 * `updated_at` is set at call time so each seed gets a fresh timestamp.
 */
export function createDefaultShopSettings(
  overrides: Partial<ShopSettings> & Record<string, unknown> = {},
): ShopSettings & Record<string, unknown> {
  return {
    shop_name: '',
    phone: '',
    address: '',
    currency: 'PKR',
    measurement_fields: [],
    pipeline_stages: DEFAULT_PIPELINE_STAGES.map((s) => ({ ...s })),
    auto_archive_days: 30,
    measurement_unit: 'Inches',
    terms_conditions: '',
    receipt_footer_text: 'Receipt is generated by Hello Darzi - 03163455358',
    updated_at: new Date().toISOString(),
    updated_by: 'system',
    ...overrides,
  };
}

/** Snapshot of defaults without a live timestamp (for static comparisons / UI fallbacks). */
export const DEFAULT_SHOP_SETTINGS: ShopSettings & Record<string, unknown> = {
  shop_name: '',
  phone: '',
  address: '',
  currency: 'PKR',
  measurement_fields: [],
  pipeline_stages: DEFAULT_PIPELINE_STAGES,
  auto_archive_days: 30,
  measurement_unit: 'Inches',
  terms_conditions: '',
  receipt_footer_text: 'Receipt is generated by Hello Darzi - 03163455358',
  updated_at: '',
  updated_by: 'system',
};
